#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
export AUDITOPS_REPO_ROOT="${AUDITOPS_REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"

_auditops_finalize_env() {
  export AUDITOPS_STATE_ROOT="${AUDITOPS_STATE_ROOT:-$AUDITOPS_REPO_ROOT/.auditops}"
  export AUDITOPS_ENV_ROOT="${AUDITOPS_ENV_ROOT:-$AUDITOPS_STATE_ROOT/env}"
  export AUDITOPS_DATA_ROOT="${AUDITOPS_DATA_ROOT:-$AUDITOPS_STATE_ROOT/data}"
  export AUDITOPS_ARTIFACT_ROOT="${AUDITOPS_ARTIFACT_ROOT:-$AUDITOPS_STATE_ROOT/artifacts}"
  export AUDITOPS_CORPUS_HOME="${AUDITOPS_CORPUS_HOME:-$AUDITOPS_STATE_ROOT/corpora}"
  export AUDITOPS_CACHE_ROOT="${AUDITOPS_CACHE_ROOT:-$AUDITOPS_STATE_ROOT/cache}"
  export AUDITOPS_LOG_ROOT="${AUDITOPS_LOG_ROOT:-$AUDITOPS_STATE_ROOT/logs}"
  export AUDITOPS_RUN_ROOT="${AUDITOPS_RUN_ROOT:-$AUDITOPS_STATE_ROOT/runs}"
  export AUDITOPS_TMP_ROOT="${AUDITOPS_TMP_ROOT:-$AUDITOPS_STATE_ROOT/tmp}"
  export AUDITOPS_MODEL_ROOT="${AUDITOPS_MODEL_ROOT:-$AUDITOPS_STATE_ROOT/models}"
  export AUDITOPS_MODEL_REGISTRY="$AUDITOPS_REPO_ROOT/config/model_revisions.json"
  export AUDITOPS_CONTAINER_ROOT="${AUDITOPS_CONTAINER_ROOT:-$AUDITOPS_STATE_ROOT/containers}"
  export AUDITOPS_BENCHMARK_ROOT="${AUDITOPS_BENCHMARK_ROOT:-$AUDITOPS_STATE_ROOT/benchmarks}"
  export AUDITOPS_PACKAGE_LOCK_FILE="${AUDITOPS_PACKAGE_LOCK_FILE:-$AUDITOPS_REPO_ROOT/requirements/auditops-py311.lock}"


  mkdir -p \
    "$AUDITOPS_ENV_ROOT" \
    "$AUDITOPS_DATA_ROOT" \
    "$AUDITOPS_ARTIFACT_ROOT" \
    "$AUDITOPS_CORPUS_HOME" \
    "$AUDITOPS_CACHE_ROOT" \
    "$AUDITOPS_LOG_ROOT" \
    "$AUDITOPS_RUN_ROOT" \
    "$AUDITOPS_TMP_ROOT"

  export PIP_CACHE_DIR="${PIP_CACHE_DIR:-$AUDITOPS_CACHE_ROOT/pip}"
  export HF_HOME="${HF_HOME:-$AUDITOPS_CACHE_ROOT/huggingface}"
  export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$AUDITOPS_CACHE_ROOT/transformers}"
  export TORCH_HOME="${TORCH_HOME:-$AUDITOPS_CACHE_ROOT/torch}"
  export TMPDIR="${TMPDIR:-$AUDITOPS_TMP_ROOT}"

  mkdir -p \
    "$PIP_CACHE_DIR" \
    "$HF_HOME" \
    "$TRANSFORMERS_CACHE" \
    "$TORCH_HOME" \
    "$TMPDIR"

  export AUDITOPS_GENERIC_ENV_LOADED=1
}

if [[ "${AUDITOPS_DEFER_FINALIZE:-0}" != "1" ]]; then
  _auditops_finalize_env
fi
